disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - todo
  - type_body_length

trailing_comma:
  mandatory_comma: true

statement_position:
  statement_mode: uncuddled_else

excluded:
  - Pods
